//
// ColorThemes.swift
// Auto-generated by ColorKit
// DO NOT EDIT MANUALLY
//

import Foundation

/// Internal color theme data loaded from design tokens
internal struct ColorThemes {
    static let data: Data? = """
{
  "Background.primary": {
    "light": "#FFFFFF",
    "dark": "#000000"
  },
  "Background.secondary": {
    "light": "#F9FAFB",
    "dark": "#111827"
  },
  "Background.tertiary": {
    "light": "#F3F4F6",
    "dark": "#1F2937"
  },
  "Text.primary": {
    "light": "#111827",
    "dark": "#FFFFFF"
  },
  "Text.secondary": {
    "light": "#4B5563",
    "dark": "#D1D5DB"
  },
  "Text.tertiary": {
    "light": "#9CA3AF",
    "dark": "#6B7280"
  },
  "Text.inverse": {
    "light": "#FFFFFF",
    "dark": "#111827"
  },
  "Brand.primary": {
    "light": "#2563EB",
    "dark": "#3B82F6"
  },
  "Brand.secondary": {
    "light": "#3B82F6",
    "dark": "#60A5FA"
  },
  "Brand.light": {
    "light": "#DBEAFE",
    "dark": "#1E3A8A"
  },
  "Status.success": {
    "light": "#16A34A",
    "dark": "#22C55E"
  },
  "Status.warning": {
    "light": "#F59E0B",
    "dark": "#F59E0B"
  },
  "Status.error": {
    "light": "#DC2626",
    "dark": "#EF4444"
  },
  "Status.info": {
    "light": "#3B82F6",
    "dark": "#60A5FA"
  },
  "Border.default": {
    "light": "#E5E7EB",
    "dark": "#374151"
  },
  "Border.strong": {
    "light": "#D1D5DB",
    "dark": "#4B5563"
  },
  "Border.focus": {
    "light": "#3B82F6",
    "dark": "#60A5FA"
  }
}
""".data(using: .utf8)
}
