//
// Colors.swift
// Auto-generated by ColorKit
// DO NOT EDIT MANUALLY
//

import Foundation

/// Auto-generated color enum from design tokens
/// Each case represents a color that supports both light and dark modes
public enum Colors: String, CaseIterable {
    case background_primary
    case background_secondary
    case background_tertiary
    case border_default
    case border_focus
    case border_strong
    case brand_light
    case brand_primary
    case brand_secondary
    case status_error
    case status_info
    case status_success
    case status_warning
    case text_inverse
    case text_primary
    case text_secondary
    case text_tertiary
}