//
// ColorThemes.swift
// Auto-generated by ColorKit
// DO NOT EDIT MANUALLY
//

import Foundation

/// Internal color theme data loaded from design tokens
internal struct ColorThemes {
    static let data: Data? = """
{
  "background_primary" : {
    "dark" : "#000000",
    "light" : "#FFFFFF"
  },
  "background_secondary" : {
    "dark" : "#111827",
    "light" : "#F9FAFB"
  },
  "background_tertiary" : {
    "dark" : "#1F2937",
    "light" : "#F3F4F6"
  },
  "border_default" : {
    "dark" : "#374151",
    "light" : "#E5E7EB"
  },
  "border_focus" : {
    "dark" : "#60A5FA",
    "light" : "#3B82F6"
  },
  "border_strong" : {
    "dark" : "#4B5563",
    "light" : "#D1D5DB"
  },
  "brand_light" : {
    "dark" : "#1E3A8A",
    "light" : "#DBEAFE"
  },
  "brand_primary" : {
    "dark" : "#3B82F6",
    "light" : "#2563EB"
  },
  "brand_secondary" : {
    "dark" : "#60A5FA",
    "light" : "#3B82F6"
  },
  "status_error" : {
    "dark" : "#EF4444",
    "light" : "#DC2626"
  },
  "status_info" : {
    "dark" : "#60A5FA",
    "light" : "#3B82F6"
  },
  "status_success" : {
    "dark" : "#22C55E",
    "light" : "#16A34A"
  },
  "status_warning" : {
    "dark" : "#F59E0B",
    "light" : "#F59E0B"
  },
  "text_inverse" : {
    "dark" : "#111827",
    "light" : "#FFFFFF"
  },
  "text_primary" : {
    "dark" : "#FFFFFF",
    "light" : "#111827"
  },
  "text_secondary" : {
    "dark" : "#D1D5DB",
    "light" : "#4B5563"
  },
  "text_tertiary" : {
    "dark" : "#6B7280",
    "light" : "#9CA3AF"
  }
}
""".data(using: .utf8)
}